import type { Metadata } from 'next'
import { Alumni_Sans, Inter } from 'next/font/google'
import Header from './shared/components/header/Header'
import Footer from './shared/components/footer/Footer'
import './styles/globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
})

const alumniSans = Alumni_Sans({
  variable: '--font-alumni-sans',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Мясная лавка',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="ru" className={`${inter.variable} ${alumniSans.variable}`}>
      <body>
        <div className="page-wrapper">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
